/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.sql.PreparedStatement;
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author marlon
 */
public class EmployerDatabase extends javax.swing.JFrame {

    /**
     * Creates new form EmployerDatabase
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel ();
    
    public EmployerDatabase() {
        initComponents();
        
        Object col[] = {"Employee ID", "First Name", "Last Name", " Gender ", "DoB", "Age", "Salary"};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        conn = EmployerDatabase.ConnectDb();
        
        updateTable ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtEmployeeID = new javax.swing.JTextField();
        jbtnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtGender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtDoB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtSalary = new javax.swing.JTextField();
        jbtnClearData = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnAddData = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Employee ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 40));

        jtxtEmployeeID.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jtxtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmployeeIDActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 340, -1));

        jbtnPrint.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 190, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Gender", "DoB", "Age", "Salary"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 127, 660, 400));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 150, 40));

        jtxtFirstName.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        getContentPane().add(jtxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 340, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 150, 40));

        jtxtLastName.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        getContentPane().add(jtxtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 340, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 150, 40));

        jtxtGender.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        getContentPane().add(jtxtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 340, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setText("DoB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 150, 40));

        jtxtDoB.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        getContentPane().add(jtxtDoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 340, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel6.setText("Age ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 150, 40));

        jtxtAge.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        getContentPane().add(jtxtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 340, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel7.setText("Salary");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 150, 40));

        jtxtSalary.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        getContentPane().add(jtxtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 340, -1));

        jbtnClearData.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jbtnClearData.setText("Clear Data");
        jbtnClearData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearDataActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnClearData, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 190, 80));

        jbtnExit.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 580, 190, 80));

        jbtnAddData.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jbtnAddData.setText("Add Data");
        jbtnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddDataActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAddData, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 190, 80));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Personnel Database Creator");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 1210, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static Connection ConnectDb(){
        try
            {
                Class.forName("org.sqlite.JDBC");
                Connection conn = DriverManager.getConnection("jdbc:sqlite:/Users/marlon/Desktop/EmployerDatabase/Employ.db");
                return conn;
                
            }
        catch (Exception e)
            
        {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
        
        }
    private void jbtnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddDataActionPerformed
        // TODO add your handling code here:
        String sql = "Insert into Employ(EmpID, Firstname, Lastname, Gender, DoB, Age, Salary) VALUES(?, ?, ?, ?, ?, ?, ?)";
        
        try
        {
            pst = conn.prepareStatement(sql);
            
            pst.setString(1, jtxtEmployeeID.getText());
            pst.setString(2, jtxtFirstName.getText());
            pst.setString(3, jtxtLastName.getText());
            pst.setString(4, jtxtGender.getText());
            pst.setString(5, jtxtDoB.getText());
            pst.setString(6, jtxtAge.getText());
            pst.setString(7, jtxtSalary.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "System Update Completed");
            
            
            pst.close();
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTable ();
                                
    }//GEN-LAST:event_jbtnAddDataActionPerformed

    private void jtxtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmployeeIDActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame ("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Employee Database",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        };
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnClearDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearDataActionPerformed
        // TODO add your handling code here:
        jtxtEmployeeID.setText(null);
        jtxtFirstName.setText(null);
        jtxtLastName.setText(null);
        jtxtGender.setText(null);
        jtxtDoB.setText(null);
        jtxtAge.setText(null);
        jtxtSalary.setText(null);
        
    }//GEN-LAST:event_jbtnClearDataActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat ("Printing in progress");
        MessageFormat footer = new MessageFormat ("Page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public void updateTable(){
        conn = EmployerDatabase.ConnectDb();
        if (conn !=null)
        {
            String sql = "EmpID, Firstname, Lastname, Gender, DoB, Age, Salary from database";
            
            try
            {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                Object[] columnData = new Object [7];
                
                while (rs.next() ){
                columnData[0] = rs.getString("EmpID");
                columnData[1] = rs.getString("Firstname");
                columnData[2] = rs.getString("Lastname");
                columnData[3] = rs.getString("Gender");
                columnData[4] = rs.getString("DoB");
                columnData[5] = rs.getString("Age");
                columnData[6] = rs.getString("Salary");
                model.addRow (columnData);
                
                }
                
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployerDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JButton jbtnAddData;
    public javax.swing.JButton jbtnClearData;
    public javax.swing.JButton jbtnExit;
    public javax.swing.JButton jbtnPrint;
    public javax.swing.JTextField jtxtAge;
    public javax.swing.JTextField jtxtDoB;
    public javax.swing.JTextField jtxtEmployeeID;
    public javax.swing.JTextField jtxtFirstName;
    public javax.swing.JTextField jtxtGender;
    public javax.swing.JTextField jtxtLastName;
    public javax.swing.JTextField jtxtSalary;
    // End of variables declaration//GEN-END:variables
}
